const ASSET_STATUS = {
  AVAILABLE: "Available",
  ALLOCATED: "Allocated",
  RESERVED: "Reserved",
  UNDER_MAINTENANCE: "Under Maintenance",
  LOST: "Lost",
  RETIRED: "Retired",
  DISPOSED: "Disposed",
  UNAVAILABLE: "Unavailable"
};

const ALLOCATION_STATUS = {
  ALLOCATED: "Allocated",
  RETURNED: "Returned"
};

const TRANSFER_STATUS = {
  REQUESTED: "Requested",
  APPROVED: "Approved",
  REJECTED: "Rejected"
};

const MAINTENANCE_STATUS = {
  PENDING: "Pending",
  APPROVED: "Approved",
  IN_PROGRESS: "In Progress",
  RESOLVED: "Resolved",
  REJECTED: "Rejected"
};

const BOOKING_STATUS = {
  UPCOMING: "Upcoming",
  CANCELLED: "Cancelled"
};

/** Manual / admin status transitions allowed via asset update. */
const ALLOWED_TRANSITIONS = {
  [ASSET_STATUS.AVAILABLE]: [
    ASSET_STATUS.ALLOCATED,
    ASSET_STATUS.RESERVED,
    ASSET_STATUS.UNDER_MAINTENANCE,
    ASSET_STATUS.RETIRED,
    ASSET_STATUS.LOST,
    ASSET_STATUS.UNAVAILABLE
  ],
  [ASSET_STATUS.ALLOCATED]: [
    ASSET_STATUS.AVAILABLE,
    ASSET_STATUS.UNDER_MAINTENANCE,
    ASSET_STATUS.LOST
  ],
  [ASSET_STATUS.RESERVED]: [ASSET_STATUS.AVAILABLE, ASSET_STATUS.ALLOCATED],
  [ASSET_STATUS.UNDER_MAINTENANCE]: [ASSET_STATUS.AVAILABLE, ASSET_STATUS.ALLOCATED],
  [ASSET_STATUS.LOST]: [ASSET_STATUS.AVAILABLE, ASSET_STATUS.RETIRED],
  [ASSET_STATUS.RETIRED]: [ASSET_STATUS.DISPOSED],
  [ASSET_STATUS.DISPOSED]: [],
  [ASSET_STATUS.UNAVAILABLE]: [ASSET_STATUS.AVAILABLE, ASSET_STATUS.RETIRED]
};

const NON_ALLOCATABLE = new Set([
  ASSET_STATUS.ALLOCATED,
  ASSET_STATUS.UNDER_MAINTENANCE,
  ASSET_STATUS.RESERVED,
  ASSET_STATUS.LOST,
  ASSET_STATUS.RETIRED,
  ASSET_STATUS.DISPOSED,
  ASSET_STATUS.UNAVAILABLE
]);

const NON_TRANSFERABLE = new Set([
  ASSET_STATUS.LOST,
  ASSET_STATUS.RETIRED,
  ASSET_STATUS.DISPOSED,
  ASSET_STATUS.UNAVAILABLE
]);

const NON_MAINTAINABLE = new Set([
  ASSET_STATUS.LOST,
  ASSET_STATUS.RETIRED,
  ASSET_STATUS.DISPOSED
]);

const NON_BOOKABLE = new Set([
  ASSET_STATUS.LOST,
  ASSET_STATUS.RETIRED,
  ASSET_STATUS.DISPOSED,
  ASSET_STATUS.UNAVAILABLE
]);

function assertTransition(from, to) {
  if (from === to) return;
  const allowed = ALLOWED_TRANSITIONS[from];
  if (!allowed || !allowed.includes(to)) {
    const err = new Error(`Invalid asset status transition from "${from}" to "${to}"`);
    err.statusCode = 400;
    throw err;
  }
}

module.exports = {
  ASSET_STATUS,
  ALLOCATION_STATUS,
  TRANSFER_STATUS,
  MAINTENANCE_STATUS,
  BOOKING_STATUS,
  ALLOWED_TRANSITIONS,
  NON_ALLOCATABLE,
  NON_TRANSFERABLE,
  NON_MAINTAINABLE,
  NON_BOOKABLE,
  assertTransition
};
